export default function Head() {
  return (
    <>
      <title>My notes</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by myself ;)" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
